import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Finishes & GREENGUARD Gold',
  description:
    'What GREENGUARD Gold measures, how Heirloom describes finishes and emissions, and how to read claims without overstating certification.',
  alternates: { canonical: '/finishes' },
};

export default function FinishesPage() {
  return (
    <div className="container doc-page">
      <p className="label-caps text-on-surface-variant">Owner&rsquo;s guide</p>
      <h1 className="headline-xl">Finishes &amp; GREENGUARD Gold</h1>
      <p className="body-lg doc-lede">The finish and emissions profile of a crib matter alongside the wood itself. This guide explains what GREENGUARD Gold means and how finish language appears on Heirloom cribs—without overstating claims.</p>
      <section><h2 className="headline-md">What GREENGUARD Gold measures</h2><p>GREENGUARD Gold is an independent, third-party certification issued by UL Solutions. It tests finished products for chemical emissions into indoor air, with a focus on volatile organic compounds (VOCs). The Gold level is the stricter of the two main GREENGUARD tiers and is designed for sensitive environments such as schools, healthcare settings, and nurseries.</p><p>A GREENGUARD Gold-certified product has been tested in controlled chambers and shown to meet low emission limits, including a very low formaldehyde threshold. The certification addresses emissions—what is released into the air—rather than a full chemical-content inventory of every component. It does not replace structural safety standards such as ASTM F1169 or CPSC crib requirements.</p><p>Retesting is part of maintaining the certification. The mark indicates ongoing verification, not a one-time self-declaration.</p></section>
      <hr className="doc-rule" />
      <section><h2 className="headline-md">Why emissions matter in a nursery</h2><p>A crib is furniture a baby may be near for long periods while sleeping and resting. Lower chemical emissions from the finished piece can support cleaner indoor air in that enclosed space. Solid hardwood construction avoids the higher resin content typical of particle board or MDF, while the finish system—including stain, topcoat, and any adhesives in joinery—contributes to the overall emissions profile.</p></section>
      <section><h2 className="headline-md">How Heirloom approaches finishes and certification</h2><ul className="doc-list"><li><strong>GREENGUARD Gold Certified</strong> (UL GREENGUARD Gold for low chemical emissions) on the Old Time Oak Collection.</li><li><strong>Non-toxic, water-based, lead-free finishes</strong> on the Fisher Quality Products Collection.</li><li>Supporting structural and regulatory standards: ASTM F1169 (full-size crib), CPSC 16 CFR 1219/1220, JPMA Certified, and CPSIA compliance where listed.</li></ul><p>We do not claim that every model carries GREENGUARD Gold. Certification is collection-specific. Always check the individual product page and the <Link href="/safety" className="doc-link">Safety page</Link> for the exact standards that apply to the style you are considering.</p><p>We also do not claim “zero-VOC” as an absolute for every finish. GREENGUARD Gold is a low-emission standard, not a zero-emission guarantee.</p></section>
      <hr className="doc-rule" />
      <section><h2 className="headline-md">Solid hardwood and finish: the complete system</h2><ol className="doc-list"><li><strong>Solid hardwood</strong> provides structural mass and avoids the high binding-resin content of many engineered boards.</li><li><strong>Finish chemistry</strong> determines much of the surface emission behavior after the piece is assembled and placed in a room.</li><li><strong>Independent testing</strong>, where present, verifies the combined result under standardized conditions.</li></ol></section>
      <section><h2 className="headline-md">Practical questions</h2><h3>Does GREENGUARD Gold mean the crib is completely chemical-free?</h3><p>No. It means the finished product has been tested and meets strict low-emission limits for a broad set of VOCs, including a low formaldehyde threshold. It is an emissions certification, not a total chemical-content ban.</p><h3>Is every Heirloom crib GREENGUARD Gold certified?</h3><p>No. GREENGUARD Gold is listed for the Old Time Oak Collection. Other collections carry non-toxic / water-based / lead-free finish language and structural safety standards. Confirm on the specific product page and Safety page.</p><h3>What about lead?</h3><p>Our finish language for the Fisher Quality Products Collection includes lead-free. Lead content in children&rsquo;s products is also regulated under CPSIA. We point to the documented standards rather than inventing additional claims.</p><h3>Where can I see the full list of standards?</h3><p>Start with our <Link href="/safety" className="doc-link">Safety page</Link>. Product pages restate the key claims that apply to that model.</p></section>
      <section><h2 className="headline-md">How to evaluate finish and emissions claims</h2><ol className="doc-list"><li>Look for specific certification names, such as UL GREENGUARD Gold, rather than vague “eco-friendly” or “non-toxic” language alone.</li><li>Confirm whether the certification applies to the finished, assembled product.</li><li>Cross-check the brand&rsquo;s Safety page for the exact collections covered.</li><li>Pair emissions language with structural standards and material disclosures.</li><li>Ask for documentation if the product page is unclear, especially before placing a deposit on a made-to-order piece.</li></ol></section>
    </div>
  );
}
