import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Safe Sleep & Crib Transition',
  description:
    'Educational safe-sleep and crib-transition summary pointing to AAP, CPSC, NIH/NICHD, and CDC—not medical advice. Informational only.',
  alternates: { canonical: '/safe-sleep' },
};

export default function SafeSleepPage() {
  return (
    <div className="container doc-page">
      <p className="label-caps text-on-surface-variant">Owner&rsquo;s guide</p>
      <h1 className="headline-xl">Safe Sleep &amp; Crib Transition</h1>
      <p className="body-lg doc-lede">Informational only—not medical advice. This page summarizes public safe-sleep guidance. Every family is different: contact your pediatrician for recommendations specific to your child, follow the manufacturer&rsquo;s instructions, and check for recalls.</p>
      <p>Creating a safe sleep environment is one of the most important things parents can do in the first year. Current guidance from the AAP and CPSC centers on a firm, flat, non-inclined sleep surface that meets federal safety standards, with nothing soft or loose in the sleep space.</p>
      <section><h2 className="headline-md">The ABCs of safe infant sleep</h2><h3>A — Alone</h3><p>Babies should sleep alone on their own sleep surface. Room-sharing—having a crib or bassinet in the parents’ room—is recommended for at least the first 6 months, and ideally up to 1 year. Bed-sharing is not recommended because of increased risk of SIDS, suffocation, or strangulation.</p><h3>B — on the Back</h3><p>Place your baby on their back for every sleep—naps and nighttime—until 1 year of age. Once a baby can roll both ways independently, they may change position during sleep; continue to start them on their back.</p><h3>C — in a Crib or other approved sleep product</h3><p>Use a crib, bassinet, portable crib, or play yard that meets current CPSC safety standards. The mattress must be firm and flat, not inclined. Surfaces with an incline greater than 10 degrees are not safe for infant sleep. Use only a tightly fitted sheet. Nothing else belongs in the sleep space.</p><h3>Bare is Best</h3><p>Keep soft objects, loose bedding, pillows, quilts, comforters, bumper pads, stuffed toys, and weighted blankets or weighted swaddles out of the crib. These items increase the risk of entrapment, suffocation, or strangulation. A wearable blanket or sleep sack is the preferred way to keep baby warm if needed.</p></section>
      <section><h2 className="headline-md">Additional guidance</h2><ul className="doc-list"><li>Move your baby to a firm, flat sleep surface as soon as practical if they fall asleep in a car seat, stroller, swing, or other sitting device.</li><li>Check <a href="https://www.saferproducts.gov/" className="doc-link">SaferProducts.gov</a> and sign up for CPSC recall notifications. Never use a crib that is broken, missing parts, or has drop-side rails.</li><li>Avoid overheating; dress baby appropriately for the room temperature.</li><li>Human milk feeding is associated with a reduced risk of SIDS; discuss feeding plans with your pediatrician.</li></ul></section>
      <hr className="doc-rule" />
      <section><h2 className="headline-md">How a compliant full-size crib supports safe sleep</h2><p>A full-size crib that meets ASTM F1169 and CPSC 16 CFR 1219 provides:</p><ul className="doc-list"><li>Fixed sides, with no drop-side rails</li><li>Slats spaced no more than 2⅜ inches apart</li><li>A firm mattress that fits tightly with no gaps</li><li>Corner posts that do not exceed allowable height</li><li>Hardware and structural integrity designed to current standards</li></ul><p>Heirloom Cribs&rsquo; Old Time Oak and Fisher Quality Products collections list the relevant certifications on the <Link href="/safety" className="doc-link">Safety page</Link>. Select models also carry GREENGUARD Gold certification for low chemical emissions. Always follow the assembly instructions and periodic hardware checks provided with your crib.</p></section>
      <section><h2 className="headline-md">When to transition from crib to toddler bed</h2><p>There is no single magic age. Most children move between approximately 18 months and 3 years. AAP and CPSC guidance point to two practical triggers for leaving the crib: reaching roughly 35 inches (89 cm) in height, or beginning to climb out of the crib.</p><ul className="doc-list"><li>The child is attempting or succeeding in climbing out of the crib.</li><li>The child has reached about 35 inches (89 cm) in height, or the crib railing is at or below chest/nipple level when the child is standing.</li><li>The child shows interest in a “big-kid bed” and has enough impulse control to stay in an open sleep space after bedtime.</li><li>Nighttime potty needs make a lower, open bed more practical.</li></ul><p>If the child is content, safe, and not climbing, many families find the transition smoother closer to age 3, when impulse control is typically stronger. Safety comes first: once climbing begins or height reaches the threshold, moving to a lower toddler bed reduces fall risk from crib height. Discuss timing with your pediatrician, especially if you are unsure whether a sign applies to your child.</p></section>
      <hr className="doc-rule" />
      <section><h2 className="headline-md">Making the transition with a 4-in-1 convertible crib</h2><ol className="doc-list"><li>Confirm that the child meets one or more readiness signs above and discuss timing with your pediatrician if needed.</li><li>Lower the mattress to its lowest setting while still in crib mode if climbing has not yet started.</li><li>When ready, install the toddler-bed conversion kit according to the manufacturer&rsquo;s instructions.</li><li>Keep the same bedtime routine. Expect some boundary-testing; calmly return the child to bed without lengthy interaction.</li><li>Child-proof the room by securing furniture, cords, and outlets, and removing hazards because the child can now leave the bed.</li><li>Continue a firm, appropriately sized mattress and fitted sheet; keep soft objects out of the sleep area during the early transition period as appropriate for the child&rsquo;s age and developmental stage.</li></ol><p>Follow the manufacturer&rsquo;s instructions for the specific crib and conversion kit. See our <Link href="/how-conversion-works" className="doc-link">4-in-1 conversion guide</Link> for product-stage information.</p></section>
      <section><h2 className="headline-md">Quick questions</h2><h3>What should be in the crib with my baby?</h3><p>Only a firm mattress that fits tightly and a fitted sheet. Nothing else—no pillows, blankets, bumpers, toys, or positioners.</p><h3>Is an inclined sleeper or rocker safe for infant sleep?</h3><p>No. Current guidance states that sleep surfaces with an incline greater than 10 degrees are not safe for infant sleep. Transfer the baby to a firm, flat surface as soon as practical.</p><h3>When is it time to stop using the crib?</h3><p>When the child begins climbing out, reaches approximately 35 inches tall, or the rail is at chest level. Most transitions occur between 18 months and 3 years; follow your child&rsquo;s cues and pediatrician guidance.</p><h3>Do Heirloom cribs meet current safety standards?</h3><p>Full-size cribs in our collections are described as meeting or exceeding the applicable ASTM and CPSC standards listed on our Safety page. Always assemble and maintain the crib according to the included instructions.</p><h3>Can the same crib become a toddler bed?</h3><p>Our 4-in-1 convertible models can convert to a toddler bed, then daybed and full-size bed, using the model-matched conversion kits and following the product documentation.</p></section>
      <section><h2 className="headline-md">Authoritative sources</h2><ul className="doc-list"><li><a href="https://www.healthychildren.org/English/ages-stages/baby/sleep/Pages/A-Parents-Guide-to-Safe-Sleep.aspx" className="doc-link">AAP / HealthyChildren.org — How to Keep Your Sleeping Baby Safe</a></li><li><a href="https://publications.aap.org/pediatrics/article/150/1/e2022057990/188304/Sleep-Related-Infant-Deaths-Updated-2022" className="doc-link">AAP Policy Statement</a></li><li><a href="https://www.cpsc.gov/SafeSleep" className="doc-link">CPSC Safe Sleep</a></li><li><a href="https://safetosleep.nichd.nih.gov/" className="doc-link">NIH/NICHD Safe to Sleep</a></li><li><a href="https://www.cdc.gov/reproductive-health/features/babies-sleep.html" className="doc-link">CDC Babies&rsquo; Sleep Safety</a></li></ul></section>
    </div>
  );
}
