import https from 'https'
import { execSync } from 'child_process'

const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const VERCEL_TOKEN = process.env.VERCEL_TOKEN
const REPO = 'awitkowski0/HeirloomSite'
const BASE_BRANCH = 'dev'

function github(path, method = 'GET', body = null) {
  return new Promise((resolve, reject) => {
    const opts = {
      hostname: 'api.github.com',
      path: `/repos/${REPO}${path}`,
      method,
      headers: {
        'User-Agent': 'opencode-feature-agent',
        'Accept': 'application/vnd.github.v3+json',
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
      },
    }
    const req = https.request(opts, (res) => {
      let data = ''
      res.on('data', (c) => data += c)
      res.on('end', () => {
        const parsed = JSON.parse(data || '{}')
        if (!res.statusCode || res.statusCode >= 300) {
          reject(new Error(`GitHub API ${res.statusCode}: ${parsed.message || data}`))
        } else {
          resolve(parsed)
        }
      })
    })
    req.on('error', reject)
    if (body) req.write(JSON.stringify(body))
    req.end()
  })
}

function vercel(path) {
  return new Promise((resolve, reject) => {
    const opts = {
      hostname: 'api.vercel.com',
      path,
      method: 'GET',
      headers: { Authorization: `Bearer ${VERCEL_TOKEN}` },
    }
    const req = https.request(opts, (res) => {
      let data = ''
      res.on('data', (c) => data += c)
      res.on('end', () => {
        const parsed = JSON.parse(data || '{}')
        if (!res.statusCode || res.statusCode >= 300) {
          reject(new Error(`Vercel API ${res.statusCode}: ${parsed.message || data}`))
        } else {
          resolve(parsed)
        }
      })
    })
    req.on('error', reject)
    req.end()
  })
}

function run(cmd) {
  return execSync(cmd, { encoding: 'utf-8' }).trim()
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms))
}

async function main() {
  const title = process.argv[2]
  if (!title) {
    console.error('Usage: node scripts/create-pr.mjs "PR title"')
    process.exit(1)
  }

  if (!GITHUB_TOKEN) {
    console.error('❌ GITHUB_TOKEN not set. Add it to .env')
    process.exit(1)
  }

  const branch = run('git rev-parse --abbrev-ref HEAD')
  if (branch === BASE_BRANCH) {
    console.error('❌ On the base branch. Create a feature branch first.')
    process.exit(1)
  }

  console.log(`\n📦 Pushing branch: ${branch}`)
  run(`git push origin ${branch}`)

  console.log(`\n🔀 Creating PR: "${title}"`)
  const pr = await github('/pulls', 'POST', {
    title,
    head: branch,
    base: BASE_BRANCH,
    body: `Automated feature PR generated by opencode.\n\nBranch: \`${branch}\``,
  })

  const prUrl = pr.html_url
  console.log(`✅ PR created: ${prUrl}`)

  if (VERCEL_TOKEN) {
    console.log(`\n⏳ Waiting for Vercel deploy...`)
    const sha = run('git rev-parse HEAD')

    for (let i = 0; i < 60; i++) {
      await sleep(5000)
      try {
        const deployments = await vercel(`/v1/deployments?meta.githubCommitSha=${sha}&limit=1`)
        const deploy = deployments.deployments?.[0]
        if (deploy) {
          if (deploy.state === 'READY') {
            const previewUrl = `https://${deploy.url}`
            console.log(`✅ Vercel deploy ready: ${previewUrl}`)
            console.log(`\n🎉 Done!`)
            console.log(`   PR:     ${prUrl}`)
            console.log(`   Deploy: ${previewUrl}`)
            return
          }
          if (deploy.state === 'ERROR') {
            console.error(`❌ Vercel deploy failed: ${deploy.error_message || 'unknown error'}`)
            break
          }
          console.log(`   State: ${deploy.state}... (waiting)`)
        }
      } catch {
        console.log('   Waiting for deploy to register...')
      }
    }
    console.log(`\n⚠️  Timed out waiting for Vercel. Check the deploy manually.`)
  }

  console.log(`\n🎉 PR created: ${prUrl}`)
}

main().catch((err) => {
  console.error(`\n❌ Error: ${err.message}`)
  process.exit(1)
})
